### ISSUE TITLE
nokia 2.3 support? (got bypass for fastboot stuff)

### ISSUE THREAD

**Issue by Frogyfucious** [Neternels/devices#1]
so, firstly 
even bootloader unlock is not possible for 2.3 via fastboot  , nor flashing, rooting and so on(there is a bypass), i got my bootloader unlocked and i can root, flash, dump, write and more. Is there a chance that there will be 2.3 support? If yes, i would be happy to show the bypass method.

**Comment by Slavfucious** [comment]
also, can twrp be ported somehow?

**Comment by 0n1cOn3** [comment]
Hi 

Thanks for your questions.
We only do kernel customizations. 
TWRP is a complete different story. Also Bootloader stuff. We can't help you there with im

Im sorry
