### ISSUE TITLE
can you guys make one for realme c15 qualcomm edition (RMX2195)

### ISSUE THREAD

**Issue by IYSTREEM** [Neternels/devices#10]
I have been trying to build one for months if you guys can do it, it'll be a big help for me , Thanks

**Comment by cyberknight777** [comment]
We don't own the device, sorry.

**Comment by IYSTREEM** [comment]
you can build it and send it to me i can test it out for you guys

**Comment by 0n1cOn3** [comment]
> you can build it and send it to me i can test it out for you guys

Please join our Telegram group for further informations.
