### ISSUE TITLE
Potential wakelock issue? [Mojito]

### ISSUE THREAD

**Issue by nikp123** [Neternels/devices#11]
Not sure if this kernel project is to blame, but I was wondering why the entire ``/proc/wakelock`` tree is missing from a ROM (the unofficial LineageOS 20/21 port for this device) that's based on this kernel. 

I've noticed a significant problem that I think might stem from this:
- Calls and notifications are irregular, they depend on apps being recently opened to receive notifications (example K-9 mail) which can become quite frustrating after a while.

While it's better than what some manufacturers do - outright break apps, this is still hindering my ability to respond in a timely fashion to incoming messages.

If it's not this then are there any avenues to look at to solve this? Thanks for maintaining this kernel btw.

**Comment by cyberknight777** [comment]
iirc /proc/wakelock depends on DebugFS or some other kernel debugging feature. Pretty sure I disabled it for a reason. If there are calls/notifs related issues, I would have gotten plentiful reports about it from other ROMs such as YAAP, PixelOS, AOSPA. So I don’t really think it’s kernel but perhaps something ROM sided, are you on vanilla by any chance? Also if you’re on Telegram, DM me there so we can talk further as most of my user base as well as Alonso (LOS unofficial dev) is on telegram so we can get others to reprod this bug.

**Comment by nikp123** [comment]
>, are you on vanilla by any chance?
Not sure what you mean.
> Also if you’re on Telegram, DM me there so we can talk further as most of my user base as well as Alonso (LOS unofficial dev) is on telegram so we can get others to reprod this bug.
I was, but I could reinstall it just for this. Good to know this btw.

**Comment by nikp123** [comment]
This also might be related to how microG behaves because I despise Google services, maybe I'm shooting myself in the foot with this.

Because the issue itself isn't that ALL of the services work or do not work, it's how some services RANDOMLY fail to notify me.

One time I may have messages arriving on time, some other times I wouldn't. Most famous example of this is Viber's call notifications, which works 50/50 percent and is by far the worst in this.

**Comment by nikp123** [comment]
Apologies in advance if my issues are app related and not anything ROM/kernel based.

**Comment by nikp123** [comment]
We've discussed this in private, and it's most likely stemming from my usage of microG :(
