### ISSUE TITLE
Xiaomi Redmi note 11s (fleur)

### ISSUE THREAD

**Issue by Runnerblade84** [Neternels/devices#2]
Hi guys, i want to contribute to create a version for fleur. Is it a good idea?

**Comment by 0n1cOn3** [comment]
Hey 😌

Do it - Only then you know if it was a good idea 🙂 

And if you got a stable Kernel and wanna join us, come to our Telegram groups for updates, help and other notifications 😀 
We will then decide if you will be accepted with your kernel or not.
