### ISSUE TITLE
Please add wifi adapter driver

### ISSUE THREAD

**Issue by mahadidot** [Neternels/devices#3]
bro please add rtl8188eus, mt7601u and more wifi adapter driver.
thanks in advanced.
waiting for ur response 🖤

**Comment by 0n1cOn3** [comment]
@mahadidot Damn, dunno what I shall answer here 🥲

**Comment by mahadidot** [comment]
my device is mojito (redmi note 10)
and i use nethunter. but i cant access my external wifi adapter.
please make mojito or sunny kernel with builin wifi adapter injection
support + external adapter drivers.
(rtl8188eus,  mt7601u and more common driver)
bluetooth driver if nedded.
.
or please gimme e proper tutorial link for modify and add drivers for
kernel.

thank you brother 🖤

**Comment by cyberknight777** [comment]
@mahadidot You need to flash the modules zip via magisk and load the modules with neternels addon app

**Comment by mahadidot** [comment]
i have already done this.
but in kali nethunter when i run
airmon-ng
here its show my external adapter (wlan3)

PHY     Interface       Driver          Chipset

phy0    p2p0            icnss           Not pci, usb, or sdio
phy0    wifi-aware0     icnss           Not pci, usb, or sdio
phy0    wlan0           icnss           Not pci, usb, or sdio
phy1    wlan1           mac80211_hwsim  Software simulator of 802.11
radio(s) for mac80211
phy2    wlan2           mac80211_hwsim  Software simulator of 802.11
radio(s) for mac80211
*=>null    wlan3           r8188eu         Realtek Semiconductor Corp.
RTL8188EUS 802.11n Wireless Network Adapter


*why there is "null" insted of "phy0 or phy1 or phy3 or phy4'?


adapter detected but i cant switch it to monitor mode why?

note : i use same adapter in my kali linux and parrot os in my pc. and
there its fully working with monitor mode and packet injection also.

please help me

**Comment by MrRob0-X** [comment]
@mahadidot you loaded the wrong module, the right one must be 8188eu.ko

**Comment by mahadidot** [comment]
yes it was my fault . i was select wrong module . after selecting rlt8xxxu
module now its fully working . thanks all ❤️
